### ISSUE TITLE
[Idea] Code generalisation — Slack bot

### ISSUE THREAD

**Issue by QDebesson** [bra1n/judgebot#120]
Hey!
I've search around the web for a bot able to answer commands for specific chapters of the rules and cards… and your project is just the perfect answer.
Sadly, I've been searching for a Slack bot, and not a Discord one.
I've been looking at your code, and I think it's pretty doable to interface different platforms and API.
Is this something you can envisage? If yes, do you need/want help?

Thanks.

**Comment by bra1n** [comment]
Hi Quentin,
thanks for your suggestion. There are already a few MTG related bots available for Slack, so maybe you can find what you're looking for there? If not, feel free to adapt judgebot to the Slack API. Unfortunately, I don't have the time to do this myself - otherwise there would be a lot more happening on this project too. ;-)
