### ISSUE TITLE
Don't require prefixes unless neecessary

### ISSUE THREAD

**Issue by KingSupernova31** [bra1n/judgebot#151]
Writing out `!card` in front of any card name that a user wants to fetch is rather laborious. This has led to a number of people in my servers asking for us to use other bots instead. Given how different the syntax is between card names and rule numbers, I don't see an issue with allowing `!Tarmogoyf` and `!100.6b` be recognized and treated as though they had the appropriate prefix.

(I'm assuming that `!card` is the most common prefix among all prefixes that apply to a `<partial cardname>`. If people actually use `!ruling` or another one more often, that should be the default instead.)

**Comment by TylerBloom** [comment]
I think this would be better served with an entirely different syntax.

Most servers that I'm on use JudgeBot in conjunction with Bolas or Scryfall. From my understanding, the only commonly used feature that JudgeBot doesn't support is the double-bracket syntax. Support for that (or something equivalent) would be ideal.

**Comment by KingSupernova31** [comment]
Scryfall's syntax still requires 4 characters, whereas `!Tarmogoyf` only takes one. I think having judgebot recognize double brackets would be a slight improvement (it's a lot faster to type `[[]]` than `!card` since the keys are all in one spot), but still less than ideal.

**Comment by bra1n** [comment]
Judgebot is not going to get a new command char (like `[`) or a syntax that would interfere with other bots, if they are also present on the server. I also don't think that having a command-less `!Tarmogoyf` pull up a card is a good idea, both because now any sentence with a `!` follow by anything but a space would trigger the bot, and because you're going to get clashes with other (future) commands where the command overlaps with a card name.
The best that could be done here would be to add an alias to card that's just one letter, like `!c` or maybe even `!!`.

**Comment by KingSupernova31** [comment]
To solve the first issue, you could have the bot not send a message if a card name isn't matched. If someone accidentally types `!apple juice`, the bot just doesn't say anything. I'm not sure if this is likely to be an issue though, is that a common typo?

An alias seems like a decent solution too, I like that.

**Comment by TylerBloom** [comment]
I think the second solution is a better idea. I was using Scryfall syntax as an example, `!!Tarmogoyf!!` seems like a pretty reasonable syntax and one that is not likely to happen accidentally.

**Comment by multimeric** [comment]
This is no longer relevant with the transition to slash commands (#159).
