### ISSUE TITLE
Edgar Charmed Groom resolves to memorabilia card instead of playable card

### ISSUE THREAD

**Issue by tosborne1215** [bra1n/judgebot#158]
`!price edgar charmed groom` results in this link and no rules text. https://scryfall.com/card/avow/59/edgar-charmed-groom-edgar-charmed-groom?utm_source=api

Expected that it would resolve to https://scryfall.com/card/vow/236/edgar-charmed-groom-edgar-markovs-coffin

**Comment by multimeric** [comment]
Right, so this is happening because by default we add `include:extras` to scryfall queries. If you do the same query on scryfall ( [`edgar charmed include:extras`](https://scryfall.com/search?q=edgar+charmed+include%3Aextras&unique=cards&as=grid&order=name)) you get the art card coming up first. And then because you used `!price` it only picks the first result. I wonder why @bra1n added this in the first place, because it seems like it would cause a lot of odd outcomes

**Comment by bra1n** [comment]
I added the extra flag by default so that silver bordered cards, planes and
other non-playable cards can also be searched directly.

**Comment by tosborne1215** [comment]
Thanks! Gonna close it!
