### ISSUE TITLE
Judgebot offline

### ISSUE THREAD

**Issue by Th3-Slengineer** [bra1n/judgebot#166]
Looks like it is offline, any thing to reccomend to try and fix if its our end?

**Comment by bra1n** [comment]
Hi @Th3-Slengineer,

this is probably caused by Discord phasing out its message reading API which is currently used by judgebot to check if someone used a `!` command. @multimeric is working on an improved judgebot that uses Slash commands and should be ready soon, so please hang tight and I'll try to restart the bot when it disconnects until then.
