### ISSUE TITLE
The bot is very unreliable for us. 

### ISSUE THREAD

**Issue by bl4ckb0l7** [bra1n/judgebot#170]
I have a small server with a handful of friends. We’d love the bot, but it’s hardly responding to commands. 
can’t tell any more details, but sometimes it works, but mostly, there is just jo respond.  Than it works again. 

What can I provide further?

**Comment by bra1n** [comment]
Hi Thomas,
I'm sorry that you're having trouble using the bot! This is, in part, caused by Discord slowly phasing out bot access to user messages, which is why @multimeric is working on slash commands in #159.
As soon as he's done with this, we'll release the new version which should have much improved usability and no longer suddenly stop working. Sorry if it still takes a while, we're working on this in our free time. :-)

**Comment by bl4ckb0l7** [comment]
No hurry, thanks for this fast update!
