### ISSUE TITLE
!ipg ddlp doesn't show downgrade options

### ISSUE THREAD

**Issue by bra1n** [bra1n/judgebot#32]
Or any other sections but "definition".

**Comment by hgarus** [comment]
I found the reason: The markup on http://blogs.magicjudges.org/rules/ipg3-5 is invalid. In the raw html around line 324 there is some weird stuff going on with those p tags and the alert-info div. It seems cheerio is not able to handle this and just gives up after reading the definition section.

Possible solutions are:
* Just fix the markup in the annotated IPG
* Switch back to jsdom and jquery, which seems to handle this without a problem.
* Use the ipg from MTG Familiar (https://sites.google.com/site/mtgfamiliar/rules/). Which is one simple page without any additional clutter. I could see parsing this once on startup which should speed up ipg queries.

I am currently favoring solution 3 since we're not using the annotations anyway.

**Comment by bra1n** [comment]
Alright, I cleaned up the page on blogs for solution number 1, however I absolutely agree that solution 3 would be the best overall, by far. @hgarus maybe tackle that in a new ticket or in #11 ?
